name: Generate Events

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate index.html
        run: |
          template=$(cat template.html)
          events_html=""
          for d in events/*/ ; do
              event_id=$(basename $d)
              event_title=$(head -n 1 "$d/description.txt")
              event_description=$(tail -n +2 "$d/description.txt")
              event_html="
                <div class='event-item'>
                    <a class='event-link' href='events/${event_id}/event.html'>
                        <h3>${event_title}</h3>
                        <p>${event_description}</p>
                    </a>
                </div>"
              events_html="${events_html}${event_html}"
          done
          index_html="${template//\{\{EVENTS\}\}/${events_html}}"
          echo "$index_html" > index.html

      - name: Generate event.html for each event
        run: |
          event_template=$(cat event_template.html)
          for d in events/*/ ; do
              event_id=$(basename $d)
              event_title=$(cat "$d/title.txt")
              event_description=$(cat "$d/description.txt")
              main_image="${d}main-image.jpg"
              
              materials_html=""
              for material in ${d}materials/* ; do
                  material_name=$(basename $material)
                  materials_html="${materials_html}<li><a href='../../${material}' download>${material_name}</a></li>"
              done

              event_html="${event_template//\{\{EVENT_TITLE\}\}/${event_title}}"
              event_html="${event_html//\{\{MAIN_IMAGE\}\}/${main_image}}"
              event_html="${event_html//\{\{EVENT_DESCRIPTION\}\}/${event_description}}"
              event_html="${event_html//\{\{EVENT_MATERIALS\}\}/${materials_html}}"

              echo "$event_html" > "${d}event.html"
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html events/*/event.html
          git commit -m 'Automatically generated index.html and event.html files'
          git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
